name: ldznet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.8
  - pip
  - numpy
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch==1.13.1+cu116
    - torchvision==0.14.1+cu116
    - torchaudio==0.13.1
    - albumentations==1.3.0
    - diffusers
    - matplotlib
    - opencv-python==4.7.0.68
    - invisible-watermark
    - imageio==2.23.0
    - pytorch-lightning==1.9.4
    - omegaconf==2.2.3
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.25.1
    - torchmetrics==0.11.1
    - kornia==0.6.7
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
